### ISSUE TITLE
Some testing scripts do not work due to missing file

### ISSUE THREAD

**Issue by ai4pharma** [brianhie/efficient-evolution#1]
Scripts for s309, regn10987, mab114 and mab114_uca in the README.md don't work because corresponding FASTA files missed in the data folder.

**Comment by brianhie** [comment]
Should be fixed now! https://github.com/brianhie/efficient-evolution/commit/4ec8d2b4f618edcaf731577513d0fda81d36954c

**Comment by ai4pharma** [comment]
Yes, it works now.
