### ISSUE TITLE
cuda device option pass-through

### ISSUE THREAD

**Issue by avilella** [brianhie/efficient-evolution#12]
Hi,
I've run efficient-evolution `recommend.py` using the 'cuda:0' device on a Linux machine that has more than one Nvidia card.

Would it be possible to add a parameter to the `recommend.py` script that points to the cuda device to use in the system where there are many?

AFAICS, the relevant statement in the fb_model.py code is:

`                        toks = toks.to(device='cuda', non_blocking=True)`

below:

```
            with torch.no_grad():
                for batch_idx, (labels, strs, toks) in enumerate(data_loader):
                    if torch.cuda.is_available():
                        toks = toks.to(device='cuda', non_blocking=True)
                    out = self.model_(
                        toks,
                        repr_layers=self.repr_layers_,
                        return_contacts=False
                    )
                    logits = out['logits'].to(device='cpu').numpy()

            output.append(logits[0])
```

I guess it could be something like:

```
bin/recommend.py --cuda cuda:2 ...
```

As an extra option,

Referring to this:
https://pytorch.org/docs/stable/notes/cuda.html#:~:text=torch.cuda%20is%20used%20to,.cuda.device%20context%20manager.

Thanks in advance.

**Comment by brianhie** [comment]
Added in PR https://github.com/brianhie/efficient-evolution/pull/14.
