### ISSUE TITLE
I downloaded the model to another file path, how do I write the command？

### ISSUE THREAD

**Issue by geng-lee** [brianhie/efficient-evolution#31]
Hi，Developer！

I downloaded the model to another file path, how do I write the command？

python bin/recommend.py $wildtype_sequence ？

Best,
Jamie

**Comment by brianhie** [comment]
Hi @geng-lee, if you do `pip install fair-esm`, the corresponding package (`esm`) should automatically download the model for you (by default, into `~/.cache/torch`). You can then run the `recommend.py` command from anywhere. Hope that helps.
